# temporarily disable notifications
notifications:
  email: false


# temporarily limit to the travis branch
branches:
  only:
    - travis

# The matrix defines the platform on which we build the wheels and run the 
# unit tests. Since we use manylinux for the linux wheels, we only need one 
# linux version.
matrix:
  include:
    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      services:
      - docker

    - os: osx


env:
  global:
    # Twine username
    - TWINE_USERNAME=__token__
    - secure: "RD7yY1LdwvOM8QYPuQQdoErYpkikwGckJL0ojUi5ZASdR6KhA7QGsMTPR/1sp+HDgCRAW9WiFvSkiw5QXjkzf6Dz2o0VkS9qtV8HwIXzMcJDWUjZON8p2NJNdC4CnN6QU3l6j7lQqCt5ScWQ6dwm5R9sEmCJ+vjkyOrtX0QbnQ2qnzrDMtndGWRDNuGuXkmlRMKuqGdEz3D4DfiKQfKVbEOwmo7DuJ6idYrEV7//eQMDNb32I9uvmBxn07VWj2v+QcJjKC97BodLgx+NTt6HsNfS+nZIL5ncFe6HSM5D5+rjw9wEh3wY7sMI+sDDmsEHQsU+d0HwUCPd1GwCG1QFu4a+nCKCOTa446Pcw63nMcd47SukTvf61zjGfJX4eNwoPcwQ7G38ZU4gnn6pWR7SWKnbXeVC5WmWGsKH/sQXY6nq9t4C8MgcP2AjmAVaSxoqfpsv+wMKXgOkpIINauwl9GeNLBx4xuDAEtpJRoOfbKh7q4n6Az9yj2Y60jefytsA4n0TLcOfmG93ajV+AICmcshroneBxHWu7VSMcJk0EiLgr/1HNYL9Tx6DjO3QwXDZO85SvD+e37UM3kawLjDhCqBpzE4qL8I4U7ODhBnZPsiakuvDCSbe5PjPLT1Rfd4jRLmLSDKq25KQVQhtSaQUjXowDqs+luobZjklDLuF/vs="

    # CleverCSV is python3.6+
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*"

    # We want to test the wheels that we build
    - CIBW_TEST_COMMAND="python -VV && python -m unittest discover -f -s {project}/tests/test_unit/"

    # Ensure C compiler is set
    - CC="gcc"

    # Use environment variable to make sure we get the right vesion of python 
    # and pip
    - PYTHON=python3
    - PIP=pip3


install:
  # On Mac, ensure we have the latest version of Python (to run cibuildwheel)
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew update;
      brew upgrade python;
    fi

  # Install CleverCSV with the test dependencies (extra_requires)
  - $PIP install -e .[tests]

  # Run the unit tests
  - $PYTHON -m unittest discover -v -f -s ./tests/test_unit

  # Remove compiled files (these conflict with cibuildwheel somehow)
  - find . -type f -iname '*.so' -print -delete


script:
  # Use our patched version of cibuildwheel
  - $PIP install -e git+git://github.com/GjjvdBurg/cibuildwheel.git@0c33a585791cf09e56240e7bb7cca21866e8885c#egg=cibuildwheel

  # Run cibuildwheel
  - cibuildwheel --output-dir wheelhouse

  # List the results
  - ls wheelhouse

  # Debug travis tag
  - echo $TRAVIS_TAG

  # Upload to PyPI if we have a tag
  - $PIP install twine
  - $PYTHON -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl

    #  # Upload to PyPI if we have a tag
    #  - |
    #    if [[ $TRAVIS_TAG ]]; then
    #      $PIP install twine
    #      $PYTHON -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
    #    fi
