language: python
python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install poetry
  - cd python && poetry install && cd ..

script:
  - cd python && python setup.py develop nosetests -w tests/test_unit/ && cd ..

