language: python
python:
  - "3.6"

install:
  - pip install --upgrade pip
  - pip install poetry
  - pushd python && poetry install || popd

script:
  - pushd python && python setup.py develop nosetests || popd

