# temporarily disable notifications
notifications:
  email: false

# temporarily limit to the travis branch
branches:
  only:
    - travis

matrix:
  include:
    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      services:
      - docker

    - os: osx
      osx_image: xcode8.3

env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*"
    - CIBW_BEFORE_BUILD="pip install --upgrade pip==18.1"
    - CIBW_TEST_COMMAND="python -VV && python -m unittest discover -f -s {project}/tests/test_unit/"
    - CC="gcc"
    - PIP=pip3
    - PYTHON=python3

install:
  - if [ "${TRAVIS_OS_NAME:-}" == "osx" ]; then
      brew update;
      brew upgrade python;
    fi
  - $PIP install --upgrade pip==18.1
  - $PYTHON setup.py build_ext --inplace
  - $PIP install -r requirements.txt
  - python -m unittest discover -v -f -s ./tests/test_unit

script:
  - $PIP install -e git+git://github.com/joerick/cibuildwheel.git@5f416b194a488b79aaab7a696e23ab6958f99932#egg=cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - ls wheelhouse
