language: python
python:
  - "3.6"
  - "3.7"

matrix:
  include:
    - os: linux
      sudo: required
      services: docker
      python: '3.6'

    - os: linux
      dist: xenial
      sudo: required
      services: docker
      python: '3.7'

    - osx:
      language: generic

env:
  global:
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*"
    - CC="gcc"
    - PIP=pip3
    - PYTHON=python3

install:
  - $PIP install --upgrade pip
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install
  - $PYTHON setup.py build_ext --inplace
  - poetry run green -v ./tests/test_unit

script:
  - $PIP install cibuildwheel==0.12.0
  - cibuildwheel --output-dir wheelhouse
