# Travis-CI configuration for CleverCSV
#

# The matrix defines the platform on which we build the wheels and run the 
# unit tests. Since we use manylinux for the linux wheels, we only need one 
# linux version.
jobs:
  include:
    - language: python
      dist: xenial
      sudo: required
      python: "3.7"
      services:
      - docker
      env:
        - CC="gcc"
        - PYTHON="python3"
        - PIP="pip3"

    - os: osx
      language: shell
      env:
        - CC="gcc"
        - PYTHON="python3"
        - PIP="pip3"

    - os: windows
      language: shell
      before_install:
        - choco install python3 --version 3.6.8 --no-progress -y
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - PYTHON="python"
        - PIP="pip"

env:
  global:
    # Twine username
    - TWINE_USERNAME=__token__
    - secure: "esChcOJ5bX2qLnkYhLVL/t3NZtlAWCJYDV6yWIg43wPV2GkUnIz01Qvrndyq4UsG6jLo7eoeuihEFV9uOfl9R202s1FWHn9rk1RNqedqfTn7o6xoVSgVMp9uf9etu9h774fO77aI4wxeYvhz0yv/c3x6O/gBy+hp01HRG0u0oCTH/Md4WhNK3N1FIGqP4DdLKLfvdrdc9Nq+frjG1UUZDLDcAU5PK+flFzaSjMZw7Q8QgeRxZdM6ZlzIsPAGpmO2Ax5Iin/i/PxHjtsH/fYjRoaN+HvDD52BIznK0gBzZJN4ubDw4k5X+QYUBzVOcqFG/Ueu64gJlyh1YX374nwcbZua73Y0FHD0tYgwQK+lejHDzHDSnnbZy0my9P0GRj521BQiIqQLKMG+8khue+RP4SsM5XbWUG/U6Da8KysFr2Vd5kUA9VPlufBb+R6ta+VsVDvQj03h0nSdL6hRkeE1u6z1OGNVpyEzCcb+bMR/+7vam39pgBL6BLOJXAD9VNDNeOdPqldO1fZKokD2J2EvYIYicBMYALCtuEzE2mhcFVyuBGbpy0onreBT8+dcQCdp6Wg4R5SiguOdtuJ2fN7StP0tk8EDAOf+QclDljgLYFugRMJoajIv/z9aCSXmWbNioDRyY5urIB9t4xyw9ZdCYpjgnv4mkaIu0x0k+0SLMaw="

    # CleverCSV is python3.6+
    - CIBW_SKIP="pp* cp27-* cp33-* cp34-* cp35-*"

    # We want to test the wheels that we build
    - CIBW_TEST_COMMAND="python -VV && python -m unittest discover -f -s {project}/tests/test_unit/"

    # We want to install the full package when testing the wheel
    - CIBW_TEST_EXTRAS="full"


install:
  # Print the Python version
  - $PYTHON -VV

  # Install CleverCSV with the test dependencies (extra_requires)
  - $PIP install -e .[full,tests]

  # Run the unit tests
  - $PYTHON -m unittest discover -v -f -s ./tests/test_unit

  # Remove compiled files (these conflict with cibuildwheel somehow)
  - if [ "${TRAVIS_OS_NAME:-}" == "linux" ]; then
      find . -type f -iname '*.so' -print -delete;
    fi


script:
  - if [[ "${TRAVIS_TAG:-}" =~ ^v[0-9]\.[0-9]\.[0-9].*$ ]]; then
      $PIP install cibuildwheel && cibuildwheel --output-dir wheelhouse && ls -1 wheelhouse;
    else
      echo "No valid git tag present so not running cibuildwheel.";
    fi

deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis_deploy.sh "${TRAVIS_TAG}" "${PIP}" "${PYTHON}"
  on:
    tags: true
