branches:
  only:
    - appveyor

environment:
  global:
    # CleverCSV requires Python 3.6+
    CIBW_BUILD: cp36-* cp37-*
    # We want to test the wheels that we build
    CIBW_TEST_COMMAND: "python -m unittest discover -f -s {project}/tests/test_unit/"
    # We use a API token for PyPI
    TWINE_USERNAME: __token__

  matrix:
    # Ensure the Python version AppVeyor uses is modern enough
    - PYTHON_VERSION: 3.7

# Does the work
build_script:
  - pip install cibuildwheel==0.12.0
  - cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python -m pip install twine
    &&
    python -m twine upload --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
    )

# Make AppVeyor return the artifacts in the web interface
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels


#branches:
#  only:
#    - appveyor
#
#platform:
#  - x64
#  - x86
#
#environment:
#  global:
#    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor_env.cmd"
#
#  matrix:
#    - PYTHON_VERSION: 3.6
#    - PYTHON_VERSION: 3.7
#
#init:
#  - set PY_VER=%PYTHON_VERSION:.=%
#  - set PYTHON=C:\PYTHON%PY_VER%
#  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)
#  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
#  - python --version
#
#install:
#  - ECHO 'Installed SDKs:'
#  - ps: 'ls "C:/Program Files/Microsoft SDKs/Windows"'
#  - pip install -e .[tests]
#
#build: false
#
#test_script:
#  - python -m unittest discover -v -f -s .\\tests\\test_unit
#
#after_test:
#  - pip install --upgrade setuptools wheel
#  - python setup.py sdist bdist_wheel --dist-dir=wheelhouse
#
#on_failure:
#  - ps: dir "env:"
#
#artifacts:
#  - path: "wheelhouse\\*.whl"
#    name: Wheels
