branches:
  only:
    - appveyor

platform:
  - x64

environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor_env.cmd"

  matrix:
    #    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.7

init:
  - set PY_VER=%PYTHON_VERSION:.=%
  - set PYTHON=C:\PYTHON%PY_VER%
  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version

install:
  - ECHO 'Installed SDKs:'
  - ps: 'ls "C:/Program Files/Microsoft SDKs/Windows"'
  - pip install --upgrade pip==18.1
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace

build: false

test_script:
  - python -m unittest discover -f -s .\\tests\\test_unit

after_test:
  - pip install --upgrade setuptools wheel
  - python setup.py sdist bdist_wheel --dist-dir=wheelhouse

on_failure:
  - ps: dir "env:"

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
