branches:
  only:
    - appveyor

environment:
  global:
    # CleverCSV requires Python 3.6+
    CIBW_BUILD: cp36-* cp37-*
    # We want to test the wheels that we build
    CIBW_TEST_COMMAND: "python -m unittest discover -f -s {project}/tests/test_unit/"
    # We use a API token for PyPI
    TWINE_USERNAME: __token__
    # Version of Python that we want to use for testing our package and 
    # running cibuildwheel.
    PYTHON_VERSION: 3.7

# Configure the default Python version set by PYTHON_VERSION
init:
  - set PY_VER=%PYTHON_VERSION:.=%
  - set PYTHON=C:\PYTHON%PY_VER%
  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python --version

# Does the work
build_script:
  # Install and test the package before we do anything else
  - pip3 install -e .[tests]
  - python3 -m unittest discover -v -f -s ./tests/test_unit
  # Extract the git tag manually from the repo
  # This is needed because the variable APPVEYOR_REPO_TAG is not set with 
  # generic git repos
  - ps: $env:GIT_TAG=$(git tag --points-at)
  # Install cibuildwheel
  - pip install cibuildwheel==0.12.0
  # Run cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  # Upload to PyPI if we have a tag set
  - >
    IF NOT "%GIT_TAG%" == ""
    (
    pip install twine
    &&
    python -m twine upload --skip-existing --verbose --repository-url https://test.pypi.org/legacy/ wheelhouse/*.whl
    )
