[tool.black]
line-length=79

[tool.isort]
profile="black"
sections=["FUTURE", "STDLIB", "TYPING", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_typing=["typing"]
force_single_line=true
lines_between_types=1

[tool.ruff]
# Detect invalid escape sequences in string literals
select = ["W605"]
