# ---- Artifact Project Settings ----

# Paths containing artifact markdown/toml files
artifact_paths = ["design"]

# Paths to exclude when loading artifacts
exclude_artifact_paths = []

# Paths containing code that has artifact links
code_paths = ["ccsv", "tests"]

# Paths to exclude when searching through code
exclude_code_paths = ["ccsv/__pycache__", "tests/__pycache__"]
