name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: 53 18 */10 * *

jobs:
  code-quality:
    name: Code quality checks for CleverCSV
    runs-on: ubuntu-latest
    steps:
      - name: Run black
        uses: psf/black@stable

      - name: Run isort
        uses: jamescurtin/isort-action@master

  python-test:
    needs: [code-quality]
    name: Unit tests for CleverCSV
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        py: [ '3.7', '3.11' ] # minimal and latest
    steps:
      - name: Install Python ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install CleverCSV
        run: pip install -e .[full,tests]

      - name: Run unit tests
        run: python -m unittest discover -v -f -s ./tests/test_unit
